# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build umalib

on:
  push:
    tags:
      - "v*"

jobs:
  on-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [13.14.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run electron:build
      - name:
      - name: Zip
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 umalib-win64-${{ github.ref }} ./dist_electron/win_unpacked/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'ref/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Uma Library Desktop ${{ github.ref }}
          body: TODO
          draft: false
          prerelease: false
          files: |
            umalib-win64-${{ github.ref }}.zip