# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build umalib

on:
  push:
    tags:
      - "v*"

jobs:
  on-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run electron:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Move
        run: move dist_electron\win-unpacked umalib
      - name: Zip
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'umalib-win64-${{ github.ref_name }}.zip'
          directory: './umalib/'
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref_name, 'ref/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Uma Library Desktop ${{ github.ref_name }}
          body: TODO
          draft: false
          prerelease: false
          files: umalib-win64-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  on-macos:
#    runs-on: macos-latest
#    strategy:
#      matrix:
#        node-version: [14.x]
#        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/